on: push
jobs: 
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Open directory
        run: |
          run: |
          ls -la
          cd ./.github
          ls -la
      - uses: ./actions/hello
        id: hello
        with:
          who-to-greet: "World"
      - run: |
          echo "Time: ${{ steps.hello.outputs.time }}"