name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: build and push to docker
        uses: docker/build-push-action@v2
        with:
          node-version: '14'
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ github.repository }}
          tag_with_ref: true
          tag_with_sha: true
          tags: ${{ github.sha }}
      - run: npm install -g bats
      - run: bats -v